### ISSUE TITLE
Repo is not linked to Docker Hub

### ISSUE THREAD

**Issue by rgov** [McBane87/docker-squid-proxy#1]
There is no link to this repo on the [Docker Hub page](https://hub.docker.com/r/distahl/squid) so it  is a bit difficult to find this page to report issues, review the Dockerfile, etc. Could it be added?

**Comment by McBane87** [comment]
Dockerhub is only showing the link if I add at least one entry for autobuilding. As I don't build the images using dockerhub, it wasn't showing the link.

Luckily I don't need to enable autobuilding for an autobuild entry. So now I've added a dummy entry and the link is now visible.
